# Generated by Django 4.0.3 on 2022-03-10 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadrunnerapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freighttype',
            name='endorsement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roadrunnerapi.endorsement'),
        ),
    ]
