# Generated by Django 4.0.3 on 2022-03-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadrunnerapi', '0002_freighttype_endorsement'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorsement',
            name='letter',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
    ]
