# Generated by Django 4.0.3 on 2022-03-10 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadrunnerapi', '0003_endorsement_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='dropoff_state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='load',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='load',
            name='is_hazardous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='load',
            name='load_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roadrunnerapi.loadstatus'),
        ),
        migrations.AlterField(
            model_name='load',
            name='pickup_state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='truck',
            name='current_state',
            field=models.CharField(max_length=2),
        ),
    ]
