# Generated by Django 4.0.3 on 2022-03-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadrunnerapi', '0004_alter_load_dropoff_state_alter_load_is_booked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='dropoff_address',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='load',
            name='pickup_address',
            field=models.CharField(default='test', max_length=300),
            preserve_default=False,
        ),
    ]
