# Generated by Django 4.0.3 on 2022-03-14 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roadrunnerapi', '0005_load_dropoff_address_load_pickup_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='dropoff_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='load',
            name='pickup_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
