# Generated by Django 4.0.3 on 2022-03-16 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roadrunnerapi', '0007_alter_load_dropoff_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truck',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='retired_on',
            field=models.DateTimeField(null=True),
        ),
    ]
