# Generated by Django 4.0.3 on 2022-03-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadrunnerapi', '0008_truck_created_on_truck_is_active_truck_retired_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='created_on',
        ),
    ]
