# Generated by Django 4.0.3 on 2022-03-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadrunnerapi', '0011_alter_truck_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='about',
            field=models.CharField(default='', max_length=3500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='established',
            field=models.DateField(null=True),
        ),
    ]
