# Generated by Django 4.0.3 on 2022-03-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadrunnerapi', '0012_appuser_about_appuser_established'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='established',
            field=models.DateField(),
        ),
    ]
