# Generated by Django 4.0.3 on 2022-03-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadrunnerapi', '0014_alter_dispatcherrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatcherrating',
            name='Rating',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
