# Generated by Django 4.0.3 on 2022-03-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadrunnerapi', '0015_alter_dispatcherrating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatcherrating',
            name='Rating',
        ),
        migrations.AddField(
            model_name='dispatcherrating',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
