# Generated by Django 4.0.3 on 2022-03-23 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadrunnerapi', '0016_remove_dispatcherrating_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadrunnerapi.load')),
                ('load_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadrunnerapi.loadstatus')),
            ],
        ),
    ]
